name: Run Tests

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    name: Run tests with Jest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
